#Este ejercicios es para Austin Neira
mensaje1 = input("Por favor ingresa tu nombre completo")
mensaje2 = input("Por favor ingresa tu fecha de nacimiento")
mensaje3 = input("Por favor ingresa tu edad")
mensaje4 = input("Porfa favor ingresa tu nacionalidad")
mensaje5 = input("Por favor ingresa tu estado civil")
mensaje6 = input("Porfa favor ingresa tu direccion")
mensaje7 = input("Por favor ingresa tu ciudad")
mensaje8 = input("Por favor ingresa tu Pais")
mensaje9 = input("Porfa favor ingresa tu telefono")
mensaje10 = input("Por favor ingresa tu correo electronico")
mensaje11= input("Porfa favor ingresa tu nacionalidad")
print("El nombre es: ",mensaje1)
print("El nacimiento es: ", mensaje2)
print("Tu edad es: ", mensaje3)
print("Tu nacionalidad es: ",mensaje4)
print("El estado civil es: ",mensaje5)
print("Tu direccion es: ",mensaje6)
print("Tu Ciudad es: ",mensaje7)
print("Tu Pais es: ",mensaje8)
print("Tu nacionalidad es: ",mensaje9)

#interger
num1 = int(input("Ingresa un numero: "))
print("El numero es: ",num1)